### ISSUE TITLE
Example for C.3 Honest representation: Georgia COVID-19 Viz

### ISSUE THREAD

**Issue by jayqi** [drivendataorg/deon#104]
The Georgia Dept. of Health made a visualization of COVID-19 cases where the x-axis was dates, but they were sorted by case count and not by time. 

https://www.vox.com/covid-19-coronavirus-us-response-trump/2020/5/18/21262265/georgia-covid-19-cases-declining-reopening

h/t @caseyfitz

**Comment by ejm714** [comment]
Closed by #119
