### ISSUE TITLE
Update Portuguese translation of checklist and examples

### ISSUE THREAD

**Issue by ejm714** [drivendataorg/deon#121]
The checklist and examples have changed based on #119. 

We need to:
- [x] rearrange Portuguese translation for the items that just moved in the examples table
- [x] add new translation for A4, the apple credit card example, and the georgia health dept example

**Comment by ejm714** [comment]
@manelsen we added a new item to the default checklist and added some new examples (and rearranged some others). Would you be able to update the Brazilian Portuguese versions of the files? 

You can see the changes to the two yml files here: https://github.com/drivendataorg/deon/pull/119/files
- checklist.yml
- examples_of_ethical_issues.yml

**Comment by manelsen** [comment]
I'm on it.

**Comment by manelsen** [comment]
Done, sorry for the delay.

**Comment by ejm714** [comment]
Thank you so much @manelsen -- excited to have these up to date!
