### ISSUE TITLE
Move to travisci.org for CI since codeship can't run against PRs submitted from forks

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/deon#76]
Codeship worked when everything we did was in a branch, but now that we have PRs from contributor forks we need to move over to travis.

**Comment by jayqi** [comment]
It looks like Codeship supports builds on PRs as of February 2019. I will update the settings in the repository.

https://blog.codeship.com/build-pull-requests/

https://documentation.codeship.com/general/projects/build_trigger/

**Comment by jayqi** [comment]
Oh I read this too quickly. 

> We have a short-list of features lined up that will all make it easier to use CodeShip for open source projects (more on that in another post), which includes PRs from forked builds and building the potential merge of a PR, but if we’d like to hear from you what else we can do to make working with PRs easier.

PRs from forked repos are _not_ yet supported.
