### ISSUE TITLE
PyPI distribution package missing LICENSE file

### ISSUE THREAD

**Issue by jayqi** [drivendataorg/deon#96]
The distribution package on PyPI is missing [LICENSE.txt](https://github.com/drivendataorg/deon/blob/master/LICENSE.txt). This can be checked by downloading and expanding the `.tar.gz` archive from the ["Download files" page](https://pypi.org/project/deon/#files). 

<img width="500" alt="Screen Shot 2020-01-15 at 6 07 31 PM" src="https://user-images.githubusercontent.com/2721979/72487302-71c2db00-37c2-11ea-8158-5a9184808a8e.png">

**Why include the license file?**

The Python Packaging Authority [says](https://packaging.python.org/tutorials/packaging-projects/#creating-a-license): 

> It’s important for every package uploaded to the Python Package Index to include a license. 

Additionally, the MIT License, which deon uses, [says](https://github.com/drivendataorg/deon/blob/master/LICENSE.txt): 

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by jayqi** [comment]
This came up in #87 because the test scripts check for the LICENSE file.

**Comment by pjbull** [comment]
@jayqi I think you just have to add it to the MANIFEST for it to be included.
