### ISSUE TITLE
Process for contributing to Examples / Resources docs

### ISSUE THREAD

**Issue by glipstein** [drivendataorg/deon#98]
Note: creation of Resources docs tracked in Issue #30 

Notes from slack discussion:

- Each example/resource should be a (closeable) issue per item, aggregated with a label (e.g., Examples or Resources)
- this would be a great thing to engage other people in contributing to deon (for instance, as a call to action at conferences or social media) if there were, say, a clean 3 step process for checking out resources/examples and submitting them to the docs
- Repeatable instructions in the readme for how to add a new example or resource to the docs, e.g.,

> Each needs to be 1) investigated to confirm it's worth including 2) summarized as a link: what it does and which Deon checklist item is applies to and 3) submitted as a PR to the docs

**Comment by glipstein** [comment]
Existing examples/resources to convert to issues once this is set up currently residing here; https://app.nuclino.com/DrivenData/Wiki/Building-Team-Resources-07efa55c-e44b-4043-9353-fa8dd019b758

**Comment by glipstein** [comment]
Moving these out of Nuclino and tracking in GH comments. They can become their own issues once this is in place. For now can add comments if there are more.

Resources
- DiCE: Counterfactual Explanations offer clarity in AI decision-making (open source library from Microsoft)
- LIME: https://arxiv.org/pdf/1602.04938.pdf
- Google open source differential privacy library: google/differential-privacy
- Algorithmic fairness: A code-based primer for public-sector data scientists
- Google What If tool: The What-If Tool: Code-Free Probing of Machine Learning Models
- Project Skater for model interpretation: Overview — skater 0 documentation

Examples
- Apply Pay New York regulator probes Apple Card algorithms for gender... 
   > “Goldman and Apple are delegating credit assessment to a black box,” Hansson said. “It’s not a gender-discrimination intent but it is a gender-discrimination outcome.” 
- Medical study (Dissecting racial bias in an algorithm used to manage the health of populations)
- Annotator bias: https://arxiv.org/abs/1908.07898v2 
- Algorithmic bias in bail hearings: https://www.nber.org/papers/w23180.pdf
- Informed consent: FB using 2FA phone number to target ads TechCrunch is now a part of Verizon Media

**Comment by ejm714** [comment]
Closed by https://github.com/drivendataorg/deon/pull/143

@glipstein for examples above that haven't been unchecked, can you either file separate issues for adding them or contribute them directly to the community-contributed tables of examples in the wiki (e.g. a lower bar than going on the website: https://github.com/drivendataorg/deon/wiki/Community-contributed-examples)

**Comment by glipstein** [comment]
great to close this! remaining boxes are fairly covered elsewhere, so i think we can leave as is
